theme: jekyll-theme-slate
title: "Introduction to Econometrics I" 
description: "This course provides a graduate level introduction to probability and statistics. The course was designed for economists starting their doctoral education. Edits, comments and suggestions are welcome."
